### ISSUE TITLE
excluding non-lausd users from the user table 

### ISSUE THREAD

**Issue by hongsudt** [mobilizingcs/monitor#19]
I talked to Brent this morning and he said that he got confused when looking at the user table on the monitoring tool since the number of users is different from what's reported on the class setup. 

If it is the Mobilize deployment, can we filter out non-lausd users with 0 responses? Of course, those that have responses should be there so # of responses will be consistent somewhere else.

**Comment by stevenolen** [comment]
Sorry just noticed this now. This is actually already done, see the code here: https://github.com/mobilizingcs/monitor/blob/master/index.js#L502-L513

I tested it as well just now and the user count matches the count found in the teacher tool. Could I have an example of this if it's happening somewhere I'm missing..?
